services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - veebot_net

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - veebot_net

networks:
  veebot_net:
    driver: bridge
